### ISSUE TITLE
No R 3.3.2 support

### ISSUE THREAD

**Issue by BlanchJe** [taddallas/metacom#10]
When trying to install the package it fails claiming there is no version available for R 3.3.2 (the most current version). Will this be released? If so, when? If not, is there a workaround?
![image](https://user-images.githubusercontent.com/22229510/27090732-0350b94c-502c-11e7-864d-9f9b104f4deb.png)

**Comment by BlanchJe** [comment]
Shoot sorry I just realized it was my own stupid mistake. It works! No issue.

**Comment by taddallas** [comment]
No worries. This is the best kind of issue. :+1:
