### ISSUE TITLE
BoundaryClump fuction: package version

### ISSUE THREAD

**Issue by DaniloCVieira** [taddallas/metacom#12]
Dear Dallas,

I am working with your package and I find out that "BoundaryClump" produces a different result from the example described in Dallas, 2014. In other words, a community before "Gleasonian - p=0.15" {metacom v1.3},  now is classified as "Clumped" - p= 0.001 {metacom v1.5}

Visually, the results from the earliar version seems to be more corret to me. Could you confirm which of the versions is correct?

I used the "varespec" data {vegan},  with default settings to compare the results. 
Thank you in advance,

Danilo Vieira

Dallas, T. 2014. Metacom: An R package for the analysis of metacommunity structure. - Ecography (Cop.). 37: 402–405.

## {metacom v1.3}
install.packages("metacom", repos="https://cran.r-project.org/src/contrib/Archive/metacom/metacom_1.3.tar.gz")
data(varespec)
BoundaryClump(varespec) ## Results from (Dallas, 2014) 
     index         P df
1 1.238462 0.1513498 41 ---------> non- significant p value- Gleasonian community 

## {metacom v1.5}
install.packages('metacom') 
require(metacom)
data(varespec)
BoundaryClump(varespec)
 name         stat
1 index  1.607692308
2     p  0.001895953 ---------> significant p value - Clumped community
3    df 21.000000000

**Comment by taddallas** [comment]
Hello Danilo. The issue I think comes from whether `BoundaryClump` was used to measure range clumping versus community clumping. Version 1.5 looks across species and measures the tendency for species distributions among sites to clump (range clumping). Version 1.3 took a community perspective, but I was told that most of the time researchers actually want to calculate the metric from the range perspective. The results are the same if you transpose the matrix. 

```
install.packages("metacom", repos="https://cran.r-project.org/src/contrib/Archive/metacom/metacom_1.3.tar.gz")
data(varespec)
BoundaryClump(t(varespec))

install.packages('metacom')
metacom::BoundaryClump(varespec)
```

Sorry for the confusion.

**Comment by DaniloCVieira** [comment]
Thank you very much for your help!
Kind regards,
