### ISSUE TITLE
Coherence and Turnover different from previous versions

### ISSUE THREAD

**Issue by RodolfoPelinson** [taddallas/metacom#13]
Hi. I ran the functions Coherence and Turnover a couple of years ago. Now, using the same null models, I can't get the same results. It appears that Coherence and Turnover are being overestimated in the Null Models causing larger values of Z-score. In the case of Turnover, the number of replacements of the original matrix is also different. Do you know what might be the problem? Maybe I am doing something wrong?

This is an example of what is happening using the ```varespect``` dataset of the ```vegan``` package in two versions of the ```metacom``` package(1.4.3 and 1.5.1):

```
install.packages("metacom")
library(metacom)

data("varespec")

Coe_r0_1.5.1 <- Coherence(varespec, method = "r0", order = T, binary = T, sims = 1000, seed = 1)
Coe_r0_1.5.1
         name       stat
1      embAbs 251.000000
2           z  57.471647
3           p   0.000000
4     simMean 437.076000
5 simVariance   3.237701
6 method = r0         NA


Coe_r1_1.5.1 <- Coherence(varespec, method = "r1", order = T, binary = T, sims = 1000, seed = 1)
Coe_r1_1.5.1
         name         stat
1      embAbs 2.510000e+02
2           z 1.339347e+01
3           p 6.602409e-41
4     simMean 4.075790e+02
5 simVariance 1.169070e+01
6 method = r1           NA


Tur_r0_1.5.1 <- Turnover(varespec, method = "r0", fill = T, binary = T, sims = 1000, seed = 1)
Tur_r0_1.5.1
         name          stat
1    turnover  6.301000e+03
2           z  2.686969e+01
3           p 4.966051e-159
4     simMean  1.430274e+04
5 simVariance  2.977981e+02
6 method = r0            NA

Tur_r0_1.5.1 <- Turnover(varespec, method = "r1", fill = T, binary = T, sims = 1000, seed = 1)
Tur_r0_1.5.1
         name         stat
1    turnover 6.301000e+03
2           z 5.448243e+00
3           p 5.086978e-08
4     simMean 1.020671e+04
5 simVariance 7.168748e+02
6 method = r1           NA


``` 
```
library(devtools)
install_version("metacom", version = "1.4.3")
library(metacom)

data("varespec")

set.seed(1)
Coe_r0 <- Coherence(varespec, method = "r0", order = T, binary = T, sims = 1000)
Coe_r0
$`EmbAbs`
[1] 251

$z
[1] 13.51749

$pval
[1] 1.233052e-41

$SimulatedMean
[1] 393.525

$SimulatedVariance
[1] 10.54374

$method
[1] "r0"


set.seed(1)
Coe_r1 <- Coherence(varespec, method = "r1", order = T, binary = T, sims = 1000)
Coe_r1
$`EmbAbs`
[1] 251

$z
[1] 5.78413

$pval
[1] 7.288854e-09

$SimulatedMean
[1] 342.861

$SimulatedVariance
[1] 15.88156

$method
[1] "r1"


set.seed(1)
Tur_r0 <- Turnover(varespec, method = "r0", binary = T, sims = 1000)
Tur_r0
$`Turnover`
[1] 5296

$z
[1] -18.96256

$pval
[1] 3.477863e-80

$SimulatedMean
[1] 449.275

$SimulatedVariance
[1] 255.5944

$Method
[1] "r0"


set.seed(1)
Tur_r1 <- Turnover(varespec, method = "r1", binary = T, sims = 1000)
Tur_r1
$`Turnover`
[1] 5296

$z
[1] -6.450244

$pval
[1] 1.1167e-10

$SimulatedMean
[1] 1565.008

$SimulatedVariance
[1] 578.4265

$Method
[1] "r1"

```

**Comment by taddallas** [comment]
This is a bit odd.  Some of the creation of the null matrices code changed on the `vegan` end and on `metacom` end awhile back, as well as some changes based on further discussions about the ordering of nulls. 

Note that even the raw value of turnover is different between the two versions, which suggests that the issue could be related to the calculation of turnover itself. :confused: 

Long story short, I'm on it, but it'll take me some time to nail down the exact issue. I would trust the most recent version of the package though.

**Comment by RodolfoPelinson** [comment]
Ok! I will wait to be sure that everything is all right then. In the meanwhile, I will trust the most recent version. Thank you very much for your answer! :relaxed:

**Comment by taddallas** [comment]
I'm closing the issue, but will continue to look into it. I think it may have to do with some changes around ordination of the null matrices (do you ordinate those or do you not?). I currently side on the side of not (because Steven Presley convinced me of this), but I had it ordinating the nulls previously. I've added some tests to each function to make sure the raw output matches the Leibold and Mikkelson 2002 paper, but this doesn't help with the odd z-values. Sorry if I'm not being of much help. :thinking:
