### ISSUE TITLE
could not find function Modularity 

### ISSUE THREAD

**Issue by loukesio** [taddallas/metacom#17]
Thank you for the nice package,

I have installed and loaded the metacom package but when I run the Modularity function I am getting this error 

```
Modularity(comm, method = "tswap", sims = 1000, scores = 1,
           order = TRUE, c = length(comm), nstarts = 100, returnModules = FALSE)
```

```
Error in Modularity(comm, method = "tswap", sims = 1000, scores = 1, order = TRUE,  : 
  could not find function "Modularity"
```
Any idea?

I got the info about the function from here https://www.rdocumentation.org/packages/metacom/versions/1.5.1/topics/Modularity

with best wishes, 
Loukas

**Comment by taddallas** [comment]
The `Modularity` function was dropped from the `metacom` package in version 1.5.2 (the newest release). You can still find it in the commit history (https://github.com/taddallas/metacom/blob/11b21bc536f5155c303aeb4250b68914e7cc9418/R/Modularity.R), but I'd recommend considering using `igraph` or the like for modularity calculation ... and working with network data generally. Best of luck!
