### ISSUE TITLE
identifystructure returns nothing when there is sig pos coherence

### ISSUE THREAD

**Issue by jslefche** [taddallas/metacom#5]
If matrix is not checkerboard or random, identifyStructure() simply prints "Positive coherence..." and returns no additional info (need to dig into if statements)

**Comment by taddallas** [comment]
A PhD student in the Netherlands pointed out some errors in the `IdentifyStructure` function. I got silly, and just re-wrote the thing, ignoring the quasi-structures. I didn't mean to step on your toes, and we can go back to the older version if you'd like. I also updated the `TestMatrices` to provide a good test of the `IdentifyStructure` function (as well as all the other package functions). 

I'm a bad collaborator,
Tad

**Comment by jslefche** [comment]
Hmm, ruh-roh! I may need to revisit my analyses then … at any rate, this is your show so thank you for letting me play around for a bit. Will update and check it out now! Carry on

J

_____________________________
Jonathan S. Lefcheck
Seagrass Ecology Lab
Virginia Institute of Marine Science
Gloucester Point, VA 23062
+1 (804) 684-7150
www.jonlefcheck.net
